# Generated by Django 5.2.5 on 2025-08-20 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Present', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('break_id', models.AutoField(primary_key=True, serialize=False)),
                ('break_start_time', models.DateTimeField()),
                ('break_end_time', models.DateTimeField(blank=True, null=True)),
                ('break_type', models.CharField(default='Regular', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='attendance.attendance')),
            ],
            options={
                'ordering': ['-break_start_time'],
            },
        ),
    ]
