# Generated by Django 5.2.5 on 2025-08-20 20:20
# Modified to only alter attendance status field

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_status'),
        ('attendance', '0003_remove_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='Present', max_length=100),
            preserve_default=False,
        ),
    ]
