# Generated by Django 5.2.5 on 2025-08-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='expected_hours',
            field=models.IntegerField(default=8, help_text='Expected working hours per day'),
        ),
    ]
